main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.start_page, name='start_page'),
    url(r'^check/$', views.check, name='check'),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.polls, name='list'),
    url(r'^(?P<poll_id>[0-9]+)/$', views.poll_detail, name='detail'),
    url(r'^(?P<poll_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls_v2/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls_v2'
urlpatterns = [
    url(r'^$', views.polls, name='list'),
    url(r'^(?P<poll_id>[0-9]+)/$', views.poll_detail, name='detail'),
    url(r'^(?P<poll_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls_v2/', include('polls_v2.urls')),
    url(r'^', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.question

    def count_choices(self):
        return self.choice_set.count()

    def count_total_votes(self):
        result = 0
        for choice in self.choice_set.all():
            result += choice.count_votes()
        return result

    def can_vote(self, ip_address):
        return not self.vote_set.filter(ip_address=ip_address).exists()

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=255)

    def count_votes(self):
        return self.vote_set.count()

    def __str__(self):
        return self.choice

class Vote(models.Model):
    ip_address = models.CharField(max_length=20, blank=False, null=False, primary_key=True)
    voter_name = models.CharField('Имя', max_length=60, blank=True, null=True)
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)

    def __str__(self):
        return self.ip_address

polls_v2/models.py
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.question

    def count_choices(self):
        return self.choice_set.count()

    def count_total_votes(self):
        result = 0
        for choice in self.choice_set.all():
            result += choice.count_votes()
        return result

    def can_vote(self, ip_address):
        return not self.vote_set.filter(ip_address=ip_address, poll=self).exists()

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=255)

    def count_votes(self):
        return self.vote_set.count()

    def __str__(self):
        return self.choice

class Vote(models.Model):
    ip_address = models.CharField(max_length=20, blank=True, null=True)
    voter_name = models.CharField('Имя', max_length=60, blank=True, null=True)
    poll = models.ForeignKey(Poll)
    choice = models.ForeignKey(Choice)

    def __str__(self):
        return self.ip_address

    class Meta:
        unique_together = ('ip_address', 'poll')

main/views.py
from django.shortcuts import render, reverse, redirect

def start_page(request):
    if request.session.get('allow') == True:
        return redirect('/polls_v2')
    return render(request, 'main/start_page.html')

def check(request):
    school_number = request.POST.get('school')
    if school_number is not None and school_number == '1285':
        request.session['allow'] = True
        return redirect('/polls_v2')
    else:
        return redirect('/')

polls/views.py
from django.shortcuts import render, redirect
from .models import Poll, Choice, Vote
from ipware.ip import get_ip

def polls(request):
    if request.session.get('allow') == False:
        return redirect('/')
    args={}
    users_ip = get_users_ip(request)
    polls = Poll.objects.all()
    args['polls'] = polls
    return render(request, 'polls/polls_list.html', args)

def poll_detail(request, poll_id):
    if request.session.get('allow') == False:
        return redirect('/')
    args={}
    poll = Poll.objects.get(pk=poll_id)
    choices = Choice.objects.filter(poll=poll).all()
    ip = get_users_ip(request)
    can_vote = poll.can_vote(ip)
    args['poll'] = poll
    args['choices'] = choices
    args['can_vote'] = can_vote
    return render(request, 'polls/poll_detail.html', args)

def vote(request, poll_id):
    if request.session.get('allow') == False:
        return redirect('/')    
    args = {}
    poll = Poll.objects.get(pk=poll_id)
    ip = get_users_ip(request)
    can_vote = poll.can_vote(ip)
    if can_vote:
        choice_id = request.POST.get('choice')
        if choice_id is not None:
            choice = Choice.objects.get(pk=choice_id)
            users_name = request.POST.get('name')
            vote = Vote(ip_address=ip, voter_name=users_name, poll=poll, choice=choice)
            vote.save()
    return poll_detail(request, poll_id)

def get_users_ip(request):
    ip = get_ip(request)
    return ip

polls_v2/views.py
from django.shortcuts import render, redirect
from .models import Poll, Choice, Vote
from ipware.ip import get_ip

def polls(request):
    if request.session.get('allow') == False:
        return redirect('/')
    args={}
    users_ip = get_users_ip(request)
    polls = Poll.objects.all()
    args['polls'] = polls
    return render(request, 'polls_v2/polls_list.html', args)

def poll_detail(request, poll_id):
    if request.session.get('allow') == False:
        return redirect('/')
    args={}
    poll = Poll.objects.get(pk=poll_id)
    choices = Choice.objects.filter(poll=poll).all()
    ip = get_users_ip(request)
    can_vote = poll.can_vote(ip)
    args['poll'] = poll
    args['choices'] = choices
    args['can_vote'] = can_vote
    return render(request, 'polls_v2/poll_detail.html', args)

def vote(request, poll_id):
    if request.session.get('allow') == False:
        return redirect('/')
    args = {}
    poll = Poll.objects.get(pk=poll_id)
    ip = get_users_ip(request)
    can_vote = poll.can_vote(ip)
    if can_vote:
        choice_id = request.POST.get('choice')
        if choice_id is not None:
            choice = Choice.objects.get(pk=choice_id)
            users_name = request.POST.get('name')
            vote = Vote(ip_address=ip, voter_name=users_name, poll=poll, choice=choice)
            vote.save()
    return poll_detail(request, poll_id)

def get_users_ip(request):
    ip = get_ip(request)
    return ip

main/templates/main/start_page.html
<form method="post" action="{% url 'main:check' %}">
    {% csrf_token %}
    <h4>Привет!</h4>
    <p><input type="text" name="school" value=""/> номер нашей школы</p>
    <p><input type='submit' value='вход'></p>
</form>

polls/templates/polls/poll_detail.html
<h2>Школа 1285, 1986-1996</h2>
<a href="{% url 'polls:list' %}">Назад</a>
<h3>{{poll}}</h3>


{% if can_vote %}
  <form method="post" onsubmit="validate()" action="{% url 'polls:vote' poll.id %}">
      {% csrf_token %}
      {% for choice in choices %}
        <input type="radio" value="{{choice.id}}" name="choice" id='{{choice.id}}'/>{{choice}}<br/>
      {% endfor %}
      <p><input type="text" name="name" value=""/> имя</p>
      <p><input type='submit' value='голосовать!'></p>
  </form>
  {% else %}Спасибо за голос!
{% endif %}

<hr/>
<h4>результаты:</h4>
{% for choice in choices %}
    {{choice}}: {{choice.count_votes}}<br/>
{% endfor %}
<p>всего: {{poll.count_total_votes}} голосов</p>

<script>
var choices = document.forms[0];
var first={{choices.0.id}};
var count={{choices.count}};
function validate() {
  var checked = false;
  for (i=first; i<=count; i++) {
    if (choices[i].checked) {
      checked = true;
      break;
    }
  }
  if (!checked) {
    alert('Определись с выбором!');
    return false;
  }
  else {
    return true;
  }
}
</script>

polls/templates/polls/polls_list.html
<h2>Школа 1285, 1986-1996</h2>
<h3>Голосования:</h3>
<ul>
{% for poll in polls %}
  <li><a href="{% url 'polls:detail' poll.id %}">{{poll}}</a>(голосов: {{poll.count_total_votes}})</li>
{% endfor %}
</ul>

polls_v2/templates/polls_v2/poll_detail.html
<h2>Школа 1285, 1986-1996</h2>
<a href="{% url 'polls_v2:list' %}">Назад</a>
<h3>{{poll}}</h3>


{% if can_vote %}
  <form method="post" onsubmit="validate()" action="{% url 'polls_v2:vote' poll.id %}">
      {% csrf_token %}
      {% for choice in choices %}
        <input type="radio" value="{{choice.id}}" name="choice" id='{{choice.id}}'/>{{choice}}<br/>
      {% endfor %}
      <p><input type="text" name="name" value=""/> имя</p>
      <p><input type='submit' value='голосовать!'></p>
  </form>
  {% else %}Спасибо за голос!
{% endif %}

<hr/>
<h4>результаты:</h4>
{% for choice in choices %}
    {{choice}}: {{choice.count_votes}}<br/>
{% endfor %}
<p>всего: {{poll.count_total_votes}} голосов</p>

<script>
var choices = document.forms[0];
var first={{choices.0.id}};
var count={{choices.count}};
function validate() {
  var checked = false;
  for (i=first; i<=count; i++) {
    if (choices[i].checked) {
      checked = true;
      break;
    }
  }
  if (!checked) {
    alert('Определись с выбором!');
    return false;
  }
  else {
    return true;
  }
}
</script>

polls_v2/templates/polls_v2/polls_list.html
<h2>Школа 1285, 1986-1996</h2>
<h3>Голосования:</h3>
<ul>
{% for poll in polls %}
  <li><a href="{% url 'polls_v2:detail' poll.id %}">{{poll}}</a>(голосов: {{poll.count_total_votes}})</li>
{% endfor %}
</ul>